# Single Experiment Configuration
# Run a single reasoning approach on a dataset

experiment:
  name: "chain_of_thought_evaluation"
  sample_count: 50
  output_dir: "./results/single_experiments"

dataset:
  name: "MrLight/bbeh-eval"

model:
  provider: "openrouter"
  name: "openai/gpt-oss-120b"
  temperature: 0.3
  max_tokens: 512
  top_p: 0.9

reasoning:
  approaches:
    - ChainOfThought
  multi_step_reflection: false
  multi_step_verification: false
  max_reasoning_calls: 5

execution:
  parallel: false
  save_checkpoints: true

output:
  formats:
    - csv
    - json
